version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'database'
    environment:
      - MONGO_INITDB_DATABASE=swarm
    volumes:
      - ./data:/data/db
    ports:
      - '27017-27019:27017-27019'
