/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SharedRouteImport } from './routes/_shared/route'
import { Route as SharedIndexImport } from './routes/_shared/index'
import { Route as SharedReportImport } from './routes/_shared/report'
import { Route as OutpostOutpostIdRouteImport } from './routes/outpost/$outpostId/route'
import { Route as CityCityIdRouteImport } from './routes/city/$cityId/route'
import { Route as OutpostOutpostIdIndexImport } from './routes/outpost/$outpostId/index'
import { Route as CityCityIdIndexImport } from './routes/city/$cityId/index'
import { Route as OutpostOutpostIdMapImport } from './routes/outpost/$outpostId/map'
import { Route as CityCityIdTroopImport } from './routes/city/$cityId/troop'
import { Route as CityCityIdTechnologyImport } from './routes/city/$cityId/technology'
import { Route as CityCityIdMapImport } from './routes/city/$cityId/map'
import { Route as CityCityIdBuildingImport } from './routes/city/$cityId/building'
import { Route as OutpostOutpostIdMovementRouteImport } from './routes/outpost/$outpostId/movement/route'
import { Route as CityCityIdMovementRouteImport } from './routes/city/$cityId/movement/route'
import { Route as OutpostOutpostIdMovementMovementIdImport } from './routes/outpost/$outpostId/movement/$movementId'
import { Route as CityCityIdMovementMovementIdImport } from './routes/city/$cityId/movement/$movementId'

// Create/Update Routes

const SharedRouteRoute = SharedRouteImport.update({
  id: '/_shared',
  getParentRoute: () => rootRoute,
} as any)

const SharedIndexRoute = SharedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedRouteRoute,
} as any)

const SharedReportRoute = SharedReportImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SharedRouteRoute,
} as any)

const OutpostOutpostIdRouteRoute = OutpostOutpostIdRouteImport.update({
  id: '/outpost/$outpostId',
  path: '/outpost/$outpostId',
  getParentRoute: () => rootRoute,
} as any)

const CityCityIdRouteRoute = CityCityIdRouteImport.update({
  id: '/city/$cityId',
  path: '/city/$cityId',
  getParentRoute: () => rootRoute,
} as any)

const OutpostOutpostIdIndexRoute = OutpostOutpostIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutpostOutpostIdRouteRoute,
} as any)

const CityCityIdIndexRoute = CityCityIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)

const OutpostOutpostIdMapRoute = OutpostOutpostIdMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => OutpostOutpostIdRouteRoute,
} as any)

const CityCityIdTroopRoute = CityCityIdTroopImport.update({
  id: '/troop',
  path: '/troop',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)

const CityCityIdTechnologyRoute = CityCityIdTechnologyImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)

const CityCityIdMapRoute = CityCityIdMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)

const CityCityIdBuildingRoute = CityCityIdBuildingImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)

const OutpostOutpostIdMovementRouteRoute =
  OutpostOutpostIdMovementRouteImport.update({
    id: '/movement',
    path: '/movement',
    getParentRoute: () => OutpostOutpostIdRouteRoute,
  } as any)

const CityCityIdMovementRouteRoute = CityCityIdMovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)

const OutpostOutpostIdMovementMovementIdRoute =
  OutpostOutpostIdMovementMovementIdImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => OutpostOutpostIdMovementRouteRoute,
  } as any)

const CityCityIdMovementMovementIdRoute =
  CityCityIdMovementMovementIdImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => CityCityIdMovementRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shared': {
      id: '/_shared'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRoute
    }
    '/city/$cityId': {
      id: '/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/city/$cityId'
      preLoaderRoute: typeof CityCityIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/outpost/$outpostId': {
      id: '/outpost/$outpostId'
      path: '/outpost/$outpostId'
      fullPath: '/outpost/$outpostId'
      preLoaderRoute: typeof OutpostOutpostIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/_shared/report': {
      id: '/_shared/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof SharedReportImport
      parentRoute: typeof SharedRouteImport
    }
    '/_shared/': {
      id: '/_shared/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SharedIndexImport
      parentRoute: typeof SharedRouteImport
    }
    '/city/$cityId/movement': {
      id: '/city/$cityId/movement'
      path: '/movement'
      fullPath: '/city/$cityId/movement'
      preLoaderRoute: typeof CityCityIdMovementRouteImport
      parentRoute: typeof CityCityIdRouteImport
    }
    '/outpost/$outpostId/movement': {
      id: '/outpost/$outpostId/movement'
      path: '/movement'
      fullPath: '/outpost/$outpostId/movement'
      preLoaderRoute: typeof OutpostOutpostIdMovementRouteImport
      parentRoute: typeof OutpostOutpostIdRouteImport
    }
    '/city/$cityId/building': {
      id: '/city/$cityId/building'
      path: '/building'
      fullPath: '/city/$cityId/building'
      preLoaderRoute: typeof CityCityIdBuildingImport
      parentRoute: typeof CityCityIdRouteImport
    }
    '/city/$cityId/map': {
      id: '/city/$cityId/map'
      path: '/map'
      fullPath: '/city/$cityId/map'
      preLoaderRoute: typeof CityCityIdMapImport
      parentRoute: typeof CityCityIdRouteImport
    }
    '/city/$cityId/technology': {
      id: '/city/$cityId/technology'
      path: '/technology'
      fullPath: '/city/$cityId/technology'
      preLoaderRoute: typeof CityCityIdTechnologyImport
      parentRoute: typeof CityCityIdRouteImport
    }
    '/city/$cityId/troop': {
      id: '/city/$cityId/troop'
      path: '/troop'
      fullPath: '/city/$cityId/troop'
      preLoaderRoute: typeof CityCityIdTroopImport
      parentRoute: typeof CityCityIdRouteImport
    }
    '/outpost/$outpostId/map': {
      id: '/outpost/$outpostId/map'
      path: '/map'
      fullPath: '/outpost/$outpostId/map'
      preLoaderRoute: typeof OutpostOutpostIdMapImport
      parentRoute: typeof OutpostOutpostIdRouteImport
    }
    '/city/$cityId/': {
      id: '/city/$cityId/'
      path: '/'
      fullPath: '/city/$cityId/'
      preLoaderRoute: typeof CityCityIdIndexImport
      parentRoute: typeof CityCityIdRouteImport
    }
    '/outpost/$outpostId/': {
      id: '/outpost/$outpostId/'
      path: '/'
      fullPath: '/outpost/$outpostId/'
      preLoaderRoute: typeof OutpostOutpostIdIndexImport
      parentRoute: typeof OutpostOutpostIdRouteImport
    }
    '/city/$cityId/movement/$movementId': {
      id: '/city/$cityId/movement/$movementId'
      path: '/$movementId'
      fullPath: '/city/$cityId/movement/$movementId'
      preLoaderRoute: typeof CityCityIdMovementMovementIdImport
      parentRoute: typeof CityCityIdMovementRouteImport
    }
    '/outpost/$outpostId/movement/$movementId': {
      id: '/outpost/$outpostId/movement/$movementId'
      path: '/$movementId'
      fullPath: '/outpost/$outpostId/movement/$movementId'
      preLoaderRoute: typeof OutpostOutpostIdMovementMovementIdImport
      parentRoute: typeof OutpostOutpostIdMovementRouteImport
    }
  }
}

// Create and export the route tree

interface SharedRouteRouteChildren {
  SharedReportRoute: typeof SharedReportRoute
  SharedIndexRoute: typeof SharedIndexRoute
}

const SharedRouteRouteChildren: SharedRouteRouteChildren = {
  SharedReportRoute: SharedReportRoute,
  SharedIndexRoute: SharedIndexRoute,
}

const SharedRouteRouteWithChildren = SharedRouteRoute._addFileChildren(
  SharedRouteRouteChildren,
)

interface CityCityIdMovementRouteRouteChildren {
  CityCityIdMovementMovementIdRoute: typeof CityCityIdMovementMovementIdRoute
}

const CityCityIdMovementRouteRouteChildren: CityCityIdMovementRouteRouteChildren =
  {
    CityCityIdMovementMovementIdRoute: CityCityIdMovementMovementIdRoute,
  }

const CityCityIdMovementRouteRouteWithChildren =
  CityCityIdMovementRouteRoute._addFileChildren(
    CityCityIdMovementRouteRouteChildren,
  )

interface CityCityIdRouteRouteChildren {
  CityCityIdMovementRouteRoute: typeof CityCityIdMovementRouteRouteWithChildren
  CityCityIdBuildingRoute: typeof CityCityIdBuildingRoute
  CityCityIdMapRoute: typeof CityCityIdMapRoute
  CityCityIdTechnologyRoute: typeof CityCityIdTechnologyRoute
  CityCityIdTroopRoute: typeof CityCityIdTroopRoute
  CityCityIdIndexRoute: typeof CityCityIdIndexRoute
}

const CityCityIdRouteRouteChildren: CityCityIdRouteRouteChildren = {
  CityCityIdMovementRouteRoute: CityCityIdMovementRouteRouteWithChildren,
  CityCityIdBuildingRoute: CityCityIdBuildingRoute,
  CityCityIdMapRoute: CityCityIdMapRoute,
  CityCityIdTechnologyRoute: CityCityIdTechnologyRoute,
  CityCityIdTroopRoute: CityCityIdTroopRoute,
  CityCityIdIndexRoute: CityCityIdIndexRoute,
}

const CityCityIdRouteRouteWithChildren = CityCityIdRouteRoute._addFileChildren(
  CityCityIdRouteRouteChildren,
)

interface OutpostOutpostIdMovementRouteRouteChildren {
  OutpostOutpostIdMovementMovementIdRoute: typeof OutpostOutpostIdMovementMovementIdRoute
}

const OutpostOutpostIdMovementRouteRouteChildren: OutpostOutpostIdMovementRouteRouteChildren =
  {
    OutpostOutpostIdMovementMovementIdRoute:
      OutpostOutpostIdMovementMovementIdRoute,
  }

const OutpostOutpostIdMovementRouteRouteWithChildren =
  OutpostOutpostIdMovementRouteRoute._addFileChildren(
    OutpostOutpostIdMovementRouteRouteChildren,
  )

interface OutpostOutpostIdRouteRouteChildren {
  OutpostOutpostIdMovementRouteRoute: typeof OutpostOutpostIdMovementRouteRouteWithChildren
  OutpostOutpostIdMapRoute: typeof OutpostOutpostIdMapRoute
  OutpostOutpostIdIndexRoute: typeof OutpostOutpostIdIndexRoute
}

const OutpostOutpostIdRouteRouteChildren: OutpostOutpostIdRouteRouteChildren = {
  OutpostOutpostIdMovementRouteRoute:
    OutpostOutpostIdMovementRouteRouteWithChildren,
  OutpostOutpostIdMapRoute: OutpostOutpostIdMapRoute,
  OutpostOutpostIdIndexRoute: OutpostOutpostIdIndexRoute,
}

const OutpostOutpostIdRouteRouteWithChildren =
  OutpostOutpostIdRouteRoute._addFileChildren(
    OutpostOutpostIdRouteRouteChildren,
  )

export interface FileRoutesByFullPath {
  '': typeof SharedRouteRouteWithChildren
  '/city/$cityId': typeof CityCityIdRouteRouteWithChildren
  '/outpost/$outpostId': typeof OutpostOutpostIdRouteRouteWithChildren
  '/report': typeof SharedReportRoute
  '/': typeof SharedIndexRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId/': typeof CityCityIdIndexRoute
  '/outpost/$outpostId/': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
}

export interface FileRoutesByTo {
  '/report': typeof SharedReportRoute
  '/': typeof SharedIndexRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId': typeof CityCityIdIndexRoute
  '/outpost/$outpostId': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_shared': typeof SharedRouteRouteWithChildren
  '/city/$cityId': typeof CityCityIdRouteRouteWithChildren
  '/outpost/$outpostId': typeof OutpostOutpostIdRouteRouteWithChildren
  '/_shared/report': typeof SharedReportRoute
  '/_shared/': typeof SharedIndexRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId/': typeof CityCityIdIndexRoute
  '/outpost/$outpostId/': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/report'
    | '/'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId/'
    | '/outpost/$outpostId/'
    | '/city/$cityId/movement/$movementId'
    | '/outpost/$outpostId/movement/$movementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/report'
    | '/'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/city/$cityId/movement/$movementId'
    | '/outpost/$outpostId/movement/$movementId'
  id:
    | '__root__'
    | '/_shared'
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/_shared/report'
    | '/_shared/'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId/'
    | '/outpost/$outpostId/'
    | '/city/$cityId/movement/$movementId'
    | '/outpost/$outpostId/movement/$movementId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SharedRouteRoute: typeof SharedRouteRouteWithChildren
  CityCityIdRouteRoute: typeof CityCityIdRouteRouteWithChildren
  OutpostOutpostIdRouteRoute: typeof OutpostOutpostIdRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  SharedRouteRoute: SharedRouteRouteWithChildren,
  CityCityIdRouteRoute: CityCityIdRouteRouteWithChildren,
  OutpostOutpostIdRouteRoute: OutpostOutpostIdRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_shared",
        "/city/$cityId",
        "/outpost/$outpostId"
      ]
    },
    "/_shared": {
      "filePath": "_shared/route.tsx",
      "children": [
        "/_shared/report",
        "/_shared/"
      ]
    },
    "/city/$cityId": {
      "filePath": "city/$cityId/route.tsx",
      "children": [
        "/city/$cityId/movement",
        "/city/$cityId/building",
        "/city/$cityId/map",
        "/city/$cityId/technology",
        "/city/$cityId/troop",
        "/city/$cityId/"
      ]
    },
    "/outpost/$outpostId": {
      "filePath": "outpost/$outpostId/route.tsx",
      "children": [
        "/outpost/$outpostId/movement",
        "/outpost/$outpostId/map",
        "/outpost/$outpostId/"
      ]
    },
    "/_shared/report": {
      "filePath": "_shared/report.tsx",
      "parent": "/_shared"
    },
    "/_shared/": {
      "filePath": "_shared/index.tsx",
      "parent": "/_shared"
    },
    "/city/$cityId/movement": {
      "filePath": "city/$cityId/movement/route.tsx",
      "parent": "/city/$cityId",
      "children": [
        "/city/$cityId/movement/$movementId"
      ]
    },
    "/outpost/$outpostId/movement": {
      "filePath": "outpost/$outpostId/movement/route.tsx",
      "parent": "/outpost/$outpostId",
      "children": [
        "/outpost/$outpostId/movement/$movementId"
      ]
    },
    "/city/$cityId/building": {
      "filePath": "city/$cityId/building.tsx",
      "parent": "/city/$cityId"
    },
    "/city/$cityId/map": {
      "filePath": "city/$cityId/map.tsx",
      "parent": "/city/$cityId"
    },
    "/city/$cityId/technology": {
      "filePath": "city/$cityId/technology.tsx",
      "parent": "/city/$cityId"
    },
    "/city/$cityId/troop": {
      "filePath": "city/$cityId/troop.tsx",
      "parent": "/city/$cityId"
    },
    "/outpost/$outpostId/map": {
      "filePath": "outpost/$outpostId/map.tsx",
      "parent": "/outpost/$outpostId"
    },
    "/city/$cityId/": {
      "filePath": "city/$cityId/index.tsx",
      "parent": "/city/$cityId"
    },
    "/outpost/$outpostId/": {
      "filePath": "outpost/$outpostId/index.tsx",
      "parent": "/outpost/$outpostId"
    },
    "/city/$cityId/movement/$movementId": {
      "filePath": "city/$cityId/movement/$movementId.tsx",
      "parent": "/city/$cityId/movement"
    },
    "/outpost/$outpostId/movement/$movementId": {
      "filePath": "outpost/$outpostId/movement/$movementId.tsx",
      "parent": "/outpost/$outpostId/movement"
    }
  }
}
ROUTE_MANIFEST_END */
