/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharedRouteRouteImport } from './routes/_shared/route'
import { Route as SharedIndexRouteImport } from './routes/_shared/index'
import { Route as SharedReportRouteImport } from './routes/_shared/report'
import { Route as OutpostOutpostIdRouteRouteImport } from './routes/outpost/$outpostId/route'
import { Route as CityCityIdRouteRouteImport } from './routes/city/$cityId/route'
import { Route as OutpostOutpostIdIndexRouteImport } from './routes/outpost/$outpostId/index'
import { Route as CityCityIdIndexRouteImport } from './routes/city/$cityId/index'
import { Route as OutpostOutpostIdMapRouteImport } from './routes/outpost/$outpostId/map'
import { Route as CityCityIdTroopRouteImport } from './routes/city/$cityId/troop'
import { Route as CityCityIdTechnologyRouteImport } from './routes/city/$cityId/technology'
import { Route as CityCityIdMapRouteImport } from './routes/city/$cityId/map'
import { Route as CityCityIdBuildingRouteImport } from './routes/city/$cityId/building'
import { Route as OutpostOutpostIdMovementRouteRouteImport } from './routes/outpost/$outpostId/movement/route'
import { Route as CityCityIdMovementRouteRouteImport } from './routes/city/$cityId/movement/route'
import { Route as OutpostOutpostIdMovementMovementIdRouteImport } from './routes/outpost/$outpostId/movement/$movementId'
import { Route as CityCityIdMovementMovementIdRouteImport } from './routes/city/$cityId/movement/$movementId'

const SharedRouteRoute = SharedRouteRouteImport.update({
  id: '/_shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedRouteRoute,
} as any)
const SharedReportRoute = SharedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SharedRouteRoute,
} as any)
const OutpostOutpostIdRouteRoute = OutpostOutpostIdRouteRouteImport.update({
  id: '/outpost/$outpostId',
  path: '/outpost/$outpostId',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityIdRouteRoute = CityCityIdRouteRouteImport.update({
  id: '/city/$cityId',
  path: '/city/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)
const OutpostOutpostIdIndexRoute = OutpostOutpostIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutpostOutpostIdRouteRoute,
} as any)
const CityCityIdIndexRoute = CityCityIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const OutpostOutpostIdMapRoute = OutpostOutpostIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => OutpostOutpostIdRouteRoute,
} as any)
const CityCityIdTroopRoute = CityCityIdTroopRouteImport.update({
  id: '/troop',
  path: '/troop',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdTechnologyRoute = CityCityIdTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdMapRoute = CityCityIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const CityCityIdBuildingRoute = CityCityIdBuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const OutpostOutpostIdMovementRouteRoute =
  OutpostOutpostIdMovementRouteRouteImport.update({
    id: '/movement',
    path: '/movement',
    getParentRoute: () => OutpostOutpostIdRouteRoute,
  } as any)
const CityCityIdMovementRouteRoute = CityCityIdMovementRouteRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => CityCityIdRouteRoute,
} as any)
const OutpostOutpostIdMovementMovementIdRoute =
  OutpostOutpostIdMovementMovementIdRouteImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => OutpostOutpostIdMovementRouteRoute,
  } as any)
const CityCityIdMovementMovementIdRoute =
  CityCityIdMovementMovementIdRouteImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => CityCityIdMovementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SharedIndexRoute
  '/city/$cityId': typeof CityCityIdRouteRouteWithChildren
  '/outpost/$outpostId': typeof OutpostOutpostIdRouteRouteWithChildren
  '/report': typeof SharedReportRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId/': typeof CityCityIdIndexRoute
  '/outpost/$outpostId/': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
}
export interface FileRoutesByTo {
  '/report': typeof SharedReportRoute
  '/': typeof SharedIndexRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId': typeof CityCityIdIndexRoute
  '/outpost/$outpostId': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shared': typeof SharedRouteRouteWithChildren
  '/city/$cityId': typeof CityCityIdRouteRouteWithChildren
  '/outpost/$outpostId': typeof OutpostOutpostIdRouteRouteWithChildren
  '/_shared/report': typeof SharedReportRoute
  '/_shared/': typeof SharedIndexRoute
  '/city/$cityId/movement': typeof CityCityIdMovementRouteRouteWithChildren
  '/outpost/$outpostId/movement': typeof OutpostOutpostIdMovementRouteRouteWithChildren
  '/city/$cityId/building': typeof CityCityIdBuildingRoute
  '/city/$cityId/map': typeof CityCityIdMapRoute
  '/city/$cityId/technology': typeof CityCityIdTechnologyRoute
  '/city/$cityId/troop': typeof CityCityIdTroopRoute
  '/outpost/$outpostId/map': typeof OutpostOutpostIdMapRoute
  '/city/$cityId/': typeof CityCityIdIndexRoute
  '/outpost/$outpostId/': typeof OutpostOutpostIdIndexRoute
  '/city/$cityId/movement/$movementId': typeof CityCityIdMovementMovementIdRoute
  '/outpost/$outpostId/movement/$movementId': typeof OutpostOutpostIdMovementMovementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/report'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId/'
    | '/outpost/$outpostId/'
    | '/city/$cityId/movement/$movementId'
    | '/outpost/$outpostId/movement/$movementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/report'
    | '/'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/city/$cityId/movement/$movementId'
    | '/outpost/$outpostId/movement/$movementId'
  id:
    | '__root__'
    | '/_shared'
    | '/city/$cityId'
    | '/outpost/$outpostId'
    | '/_shared/report'
    | '/_shared/'
    | '/city/$cityId/movement'
    | '/outpost/$outpostId/movement'
    | '/city/$cityId/building'
    | '/city/$cityId/map'
    | '/city/$cityId/technology'
    | '/city/$cityId/troop'
    | '/outpost/$outpostId/map'
    | '/city/$cityId/'
    | '/outpost/$outpostId/'
    | '/city/$cityId/movement/$movementId'
    | '/outpost/$outpostId/movement/$movementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SharedRouteRoute: typeof SharedRouteRouteWithChildren
  CityCityIdRouteRoute: typeof CityCityIdRouteRouteWithChildren
  OutpostOutpostIdRouteRoute: typeof OutpostOutpostIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shared': {
      id: '/_shared'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SharedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shared/': {
      id: '/_shared/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof SharedRouteRoute
    }
    '/_shared/report': {
      id: '/_shared/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof SharedReportRouteImport
      parentRoute: typeof SharedRouteRoute
    }
    '/outpost/$outpostId': {
      id: '/outpost/$outpostId'
      path: '/outpost/$outpostId'
      fullPath: '/outpost/$outpostId'
      preLoaderRoute: typeof OutpostOutpostIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$cityId': {
      id: '/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/city/$cityId'
      preLoaderRoute: typeof CityCityIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outpost/$outpostId/': {
      id: '/outpost/$outpostId/'
      path: '/'
      fullPath: '/outpost/$outpostId/'
      preLoaderRoute: typeof OutpostOutpostIdIndexRouteImport
      parentRoute: typeof OutpostOutpostIdRouteRoute
    }
    '/city/$cityId/': {
      id: '/city/$cityId/'
      path: '/'
      fullPath: '/city/$cityId/'
      preLoaderRoute: typeof CityCityIdIndexRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/outpost/$outpostId/map': {
      id: '/outpost/$outpostId/map'
      path: '/map'
      fullPath: '/outpost/$outpostId/map'
      preLoaderRoute: typeof OutpostOutpostIdMapRouteImport
      parentRoute: typeof OutpostOutpostIdRouteRoute
    }
    '/city/$cityId/troop': {
      id: '/city/$cityId/troop'
      path: '/troop'
      fullPath: '/city/$cityId/troop'
      preLoaderRoute: typeof CityCityIdTroopRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/technology': {
      id: '/city/$cityId/technology'
      path: '/technology'
      fullPath: '/city/$cityId/technology'
      preLoaderRoute: typeof CityCityIdTechnologyRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/map': {
      id: '/city/$cityId/map'
      path: '/map'
      fullPath: '/city/$cityId/map'
      preLoaderRoute: typeof CityCityIdMapRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/city/$cityId/building': {
      id: '/city/$cityId/building'
      path: '/building'
      fullPath: '/city/$cityId/building'
      preLoaderRoute: typeof CityCityIdBuildingRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/outpost/$outpostId/movement': {
      id: '/outpost/$outpostId/movement'
      path: '/movement'
      fullPath: '/outpost/$outpostId/movement'
      preLoaderRoute: typeof OutpostOutpostIdMovementRouteRouteImport
      parentRoute: typeof OutpostOutpostIdRouteRoute
    }
    '/city/$cityId/movement': {
      id: '/city/$cityId/movement'
      path: '/movement'
      fullPath: '/city/$cityId/movement'
      preLoaderRoute: typeof CityCityIdMovementRouteRouteImport
      parentRoute: typeof CityCityIdRouteRoute
    }
    '/outpost/$outpostId/movement/$movementId': {
      id: '/outpost/$outpostId/movement/$movementId'
      path: '/$movementId'
      fullPath: '/outpost/$outpostId/movement/$movementId'
      preLoaderRoute: typeof OutpostOutpostIdMovementMovementIdRouteImport
      parentRoute: typeof OutpostOutpostIdMovementRouteRoute
    }
    '/city/$cityId/movement/$movementId': {
      id: '/city/$cityId/movement/$movementId'
      path: '/$movementId'
      fullPath: '/city/$cityId/movement/$movementId'
      preLoaderRoute: typeof CityCityIdMovementMovementIdRouteImport
      parentRoute: typeof CityCityIdMovementRouteRoute
    }
  }
}

interface SharedRouteRouteChildren {
  SharedReportRoute: typeof SharedReportRoute
  SharedIndexRoute: typeof SharedIndexRoute
}

const SharedRouteRouteChildren: SharedRouteRouteChildren = {
  SharedReportRoute: SharedReportRoute,
  SharedIndexRoute: SharedIndexRoute,
}

const SharedRouteRouteWithChildren = SharedRouteRoute._addFileChildren(
  SharedRouteRouteChildren,
)

interface CityCityIdMovementRouteRouteChildren {
  CityCityIdMovementMovementIdRoute: typeof CityCityIdMovementMovementIdRoute
}

const CityCityIdMovementRouteRouteChildren: CityCityIdMovementRouteRouteChildren =
  {
    CityCityIdMovementMovementIdRoute: CityCityIdMovementMovementIdRoute,
  }

const CityCityIdMovementRouteRouteWithChildren =
  CityCityIdMovementRouteRoute._addFileChildren(
    CityCityIdMovementRouteRouteChildren,
  )

interface CityCityIdRouteRouteChildren {
  CityCityIdMovementRouteRoute: typeof CityCityIdMovementRouteRouteWithChildren
  CityCityIdBuildingRoute: typeof CityCityIdBuildingRoute
  CityCityIdMapRoute: typeof CityCityIdMapRoute
  CityCityIdTechnologyRoute: typeof CityCityIdTechnologyRoute
  CityCityIdTroopRoute: typeof CityCityIdTroopRoute
  CityCityIdIndexRoute: typeof CityCityIdIndexRoute
}

const CityCityIdRouteRouteChildren: CityCityIdRouteRouteChildren = {
  CityCityIdMovementRouteRoute: CityCityIdMovementRouteRouteWithChildren,
  CityCityIdBuildingRoute: CityCityIdBuildingRoute,
  CityCityIdMapRoute: CityCityIdMapRoute,
  CityCityIdTechnologyRoute: CityCityIdTechnologyRoute,
  CityCityIdTroopRoute: CityCityIdTroopRoute,
  CityCityIdIndexRoute: CityCityIdIndexRoute,
}

const CityCityIdRouteRouteWithChildren = CityCityIdRouteRoute._addFileChildren(
  CityCityIdRouteRouteChildren,
)

interface OutpostOutpostIdMovementRouteRouteChildren {
  OutpostOutpostIdMovementMovementIdRoute: typeof OutpostOutpostIdMovementMovementIdRoute
}

const OutpostOutpostIdMovementRouteRouteChildren: OutpostOutpostIdMovementRouteRouteChildren =
  {
    OutpostOutpostIdMovementMovementIdRoute:
      OutpostOutpostIdMovementMovementIdRoute,
  }

const OutpostOutpostIdMovementRouteRouteWithChildren =
  OutpostOutpostIdMovementRouteRoute._addFileChildren(
    OutpostOutpostIdMovementRouteRouteChildren,
  )

interface OutpostOutpostIdRouteRouteChildren {
  OutpostOutpostIdMovementRouteRoute: typeof OutpostOutpostIdMovementRouteRouteWithChildren
  OutpostOutpostIdMapRoute: typeof OutpostOutpostIdMapRoute
  OutpostOutpostIdIndexRoute: typeof OutpostOutpostIdIndexRoute
}

const OutpostOutpostIdRouteRouteChildren: OutpostOutpostIdRouteRouteChildren = {
  OutpostOutpostIdMovementRouteRoute:
    OutpostOutpostIdMovementRouteRouteWithChildren,
  OutpostOutpostIdMapRoute: OutpostOutpostIdMapRoute,
  OutpostOutpostIdIndexRoute: OutpostOutpostIdIndexRoute,
}

const OutpostOutpostIdRouteRouteWithChildren =
  OutpostOutpostIdRouteRoute._addFileChildren(
    OutpostOutpostIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SharedRouteRoute: SharedRouteRouteWithChildren,
  CityCityIdRouteRoute: CityCityIdRouteRouteWithChildren,
  OutpostOutpostIdRouteRoute: OutpostOutpostIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
